name: Upgrade NPM packages

on:
  workflow_dispatch:

  schedule:
    - cron: "0 3 * * *"

jobs:
  upgrade-packages:
    name: Upgrade packages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          repository: Tapioca-DAO/Tapioca-front

      - name: Set up Node.js âš™ï¸
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Check outdated
        run: npm install -g npm-check-updates

      - name: Upgrade packages ğŸ”€
        run: npx npm-check-updates -u 

      - name: Commit and create PR ğŸ”€
        uses: peter-evans/create-pull-request@v3
        with:
          title: "build(deps): renovate NPM packages (automated)"
          branch: "build-deps-renovate-npm-packages-automated"
          commit-message: "build(deps): renovate NPM packages (automated)"
